cubes:
  - name: products
    sql_table: product_base_info_all.dim_product_basic_info_all
    
    dimensions:
      - name: spu_id
        sql: spu_id
        type: string
        primary_key: true
      
      - name: sku_id
        sql: sku_id
        type: string
      
      - name: sku_name
        sql: sku_name
        type: string
      
      - name: brand
        sql: brand
        type: string
      
      - name: title
        sql: title
        type: string
      
      - name: category_level1
        sql: category_level1
        type: string
      
      - name: category_level2
        sql: category_level2
        type: string
      
      - name: status
        sql: status
        type: string
      
      - name: season
        sql: season
        type: string
      
      - name: supplier
        sql: supplier
        type: string
      
      - name: image
        sql: image
        type: string
      
      - name: updated_at
        sql: updated_at
        type: time
      
      - name: first_order_date
        sql: first_order_date
        type: time
      
      - name: listing_date
        sql: listing_date
        type: time
      
      - name: unlisting_date
        sql: unlisting_date
        type: time
      
      - name: fob_price
        sql: fob_price
        type: number
      
      - name: gross_weight
        sql: gross_weight
        type: number
      
      - name: net_weight
        sql: net_weight
        type: number
    
    measures:
      - name: product_count
        type: count
        description: Total number of products
