views:
  - name: lingmao_proofing_requirement_view
    description: "领猫打样需求视图（已应用筛选器：排除待定来源）"
    
    cubes:
      - join_path: lingmao_proofing_requirement
        includes:
          - id
          - sample_code
          - sample_name
          - img_url
          - planing_name
          - research_archive_state_desc
          - template_type
          - audit_state_value
          - proofing_mode_name
          - sample_progress
          - review_progress
          - review
          - proofing_code
          - supplier_name
          - designer
          - brand_name
          - year_name
          - band_name
          - category
          - source_name
          - creator_name
          - creation_time
          - last_modification_time
          - color_code
          - sku_code
          - spu_id
          - sample_plan_start
          - sample_plan_end
          - sample_actual_start
          - sample_actual_end
          - review_plan_start
          - review_plan_end
          - review_actual_start
          - review_actual_end
          - count
          - msrp
          - fob_price
          - shipping_weight
          - exclude_pending_source
    
    access_policy:
      - role: "*"
        row_level:
          filters:
            - and:
              - member: exclude_pending_source
                operator: equals
                values: [true]
