views:
  - name: po_cost_filtered_view
    description: 聚水潭采购入库概况；成品采购成本汇总视图（已过滤）- 仅包含成品、2025-02-28之后、已确认/完成状态、非返修/代售订单
    
    cubes:
      - join_path: po_cost
        includes:
          # 维度字段
          - po_id
          - status
          - item_type
          - labels
          - is_finished
          - seller
          - seller_shorted
          - po_date
          - po_year_month
          
          # 指标字段
          - count
          - sum_qty
          - sum_inqty
          - sum_uninqty
          - completion_rate
          - sum_price
          - po_unreceived_delay_cost
          - po_received_delay_cost
          - total_delay_cost
          
          # 筛选条件（segment）
          - finished_products_segment
